det-> ["a"]
det-> ["a","few"]
det-> ["a","little"]
det-> ["all"]
det-> ["another"]
det-> ["any"]
det-> ["anybody"]
det-> ["anyone"]
det-> ["anything"]
det-> ["anywhere"]
det-> ["both"]
det-> ["certain"]
det-> ["each"]
det-> ["either"]
det-> ["enough"]
det-> ["every"]
det-> ["everybody"]
det-> ["everyone"]
det-> ["everything"]
det-> ["everywhere"]
det-> ["few"]
det-> ["fewer"]
det-> ["fewest"]
det-> ["last"]
det-> ["least"]
det-> ["less"]
det-> ["little"]
det-> ["many"]
det-> ["many","a"]
det-> ["more"]
det-> ["most"]
det-> ["much"]
det-> ["neither"]
det-> ["next"]
det-> ["no"]
det-> ["no","one"]
det-> ["nobody"]
det-> ["none"]
det-> ["nothing"]
det-> ["nowhere"]
det-> ["once"]
det-> ["one"]
det-> ["said"]
det-> ["several"]
det-> ["some"]
det-> ["somebody"]
det-> ["something"]
det-> ["somewhere"]
det-> ["sufficient"]
det-> ["that"]
det-> ["the"]
det-> ["these"]
det-> ["this"]
det-> ["those"]
det-> ["three"]
det-> ["thrice"]
det-> ["twice"]
det-> ["two"]
det-> ["us"]
det-> ["various"]
det-> ["we"]
det-> ["what"]
det-> ["whatever"]
det-> ["which"]
det-> ["whichever"]
det-> ["you"]
det-> ["zero"]

conj->["For"]
conj->["And"]
conj->["Nor"]
conj->["But"]
conj->["Or"]
conj->["Yet"]
conj->["So"]
conj->["although"]
conj->["after"]
conj->["as"]
conj->["while"]
conj->["when"]
conj->["whereas"]
conj->["whenever"]
conj->["wherever"]
conj->["whether"]
conj->["how"]
conj->["if"]
conj->["in","case"]
conj->["in","order","that"]
cinj->["in","order","to"]
conj->["though"]
conj->["even","though"]
conj->["even","if"]
conj->["because"]
conj->["before"]
conj->["until"]
conj->["unless"]
conj->["since"]
conj->["so"]
conj->["so","that"]
conj->["Not","only"]
conj->["but","also"]
conj->["As"]
conj->["as"]
conj->["Both"]
conj->["and"]
conj->["Either"]
conj->["or"]
conj->["Whether"]
conj->["Neither"]
conj->["nor"]
conj->["Not"]
conj->["but"]
conj->["Such"]
conj->["that"]
conj->["Scarcely"]
conj->["when"]
conj->["As","many"]
conj->["Rather"]
conj->["than"]
conj->["No","sooner"]
conj->["Accordingly"]
conj->["After"]
conj->["Also"]
conj->["Before"]
conj->["Besides"]
conj->["Consequently"]
conj->["Conversely"]
conj->["Finally"]
conj->["Furthermore"]
conj->["Hence"]
conj->["However"]
conj->["Indeed"]
conj->["Instead"]
conj->["Likewise"]
conj->["Meanwhile"]
conj->["Moreover"]
conj->["Nevertheless"]
conj->["Next"]
conj->["Nonetheless"]
conj->["Otherwise"]
conj->["Similarly"]
conj->["Still"]
conj->["Subsequently"]
conj->["Then"]
conj->["Therefore"]
conj->["Thus"]
